name: Compile

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile notebook
        uses: xu-cheng/latex-action@v2
        with:
          latexmk_shell_escape: true
          latexmk_use_lualatex: true
          root_file: src/notebook.tex
      - name: Upload notebook
        uses: actions/upload-artifact@v3
        with:
          name: swerc
          path: notebook.pdf

