name: Compile

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo run --release compile
    - uses: actions/upload-artifact@v2
      name: Archive artifacts
      with:
        name: swerc
        path: build/swerc.pdf
