name: Compile

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Compile
      uses: actions-rs/cargo@v1
      with:
        command: run
        args: --release -- compile
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: swerc
        path: build/swerc.pdf
