name: Compile

on:
  push:
    paths:
      - 'src/**'
  pull_request:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Compile notebook
        uses: xu-cheng/latex-action@v3
        with:
          latexmk_use_lualatex: true
          args: -pdf -shell-escape -file-line-error  -interaction=nonstopmode
          root_file: src/notebook.tex
      - name: Upload notebook
        uses: actions/upload-artifact@v3
        with:
          name: swerc
          path: notebook.pdf

